# Generated by Django 6.1.1 on 2026-09-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=10, verbose_name='發送者')),
                ('content', models.TextField(verbose_name='對話內容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='對話時間')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
